server:
  port: 8100
  shutdown: graceful

spring:
  datasource:
    #hikari:
      #schema: public
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    #jdbc:postgresql://172.17.0.2:5432/postgres
    #jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: hhbs77
    platform: portgres
    initialization-mode: always


  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
      ddl-auto: validate
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: info



